import * as Icons from "lucide-react";

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  Workflow: Icons.Workflow,
  Brain: Icons.Brain,
  Building2: Icons.Building2,
  Users: Icons.Users,
  Plug: Icons.Plug,
  Zap: Icons.Zap,
  GitBranch: Icons.GitBranch,
  Network: Icons.Network,
  Sparkles: Icons.Sparkles,
  Bot: Icons.Bot,
  Gem: Icons.Gem,
  MessageCircle: Icons.MessageCircle,
  Mail: Icons.Mail,
  Target: Icons.Target,
  Calendar: Icons.Calendar,
  MessagesSquare: Icons.MessagesSquare,
  Mic: Icons.Mic,
  Headphones: Icons.Headphones,
  Settings: Icons.Settings,
  Database: Icons.Database,
  BarChart3: Icons.BarChart3,
  Globe: Icons.Globe,
  Lightbulb: Icons.Lightbulb,
  Phone: Icons.Phone,
  PhoneCall: Icons.PhoneCall,
  Server: Icons.Server,
  Radio: Icons.Radio,
  HardDrive: Icons.HardDrive,
  Wifi: Icons.Wifi,
  Disc: Icons.Disc,
  Route: Icons.Route,
  ListTree: Icons.ListTree,
  Cable: Icons.Cable,
  Layers: Icons.Layers,
  FastForward: Icons.FastForward,
  StepForward: Icons.StepForward,
  PhoneIncoming: Icons.PhoneIncoming,
  PhoneOutgoing: Icons.PhoneOutgoing,
  Cloud: Icons.Cloud,
  LineChart: Icons.LineChart,
  Link: Icons.Link,
  Repeat: Icons.Repeat,
  LayoutDashboard: Icons.LayoutDashboard,
  Home: Icons.Home,
  HeartPulse: Icons.HeartPulse,
  Shield: Icons.Shield,
  GraduationCap: Icons.GraduationCap,
  ShoppingCart: Icons.ShoppingCart,
  Factory: Icons.Factory,
  Truck: Icons.Truck,
  Landmark: Icons.Landmark,
  Hotel: Icons.Hotel,
  Building: Icons.Building,
  Store: Icons.Store,
  UserSearch: Icons.UserSearch,
  Scale: Icons.Scale,
  Award: Icons.Award,
  Rocket: Icons.Rocket,
  Clock: Icons.Clock,
  Puzzle: Icons.Puzzle,
  DollarSign: Icons.DollarSign,
  Lock: Icons.Lock,
  TrendingUp: Icons.TrendingUp,
  FileText: Icons.FileText,
  LifeBuoy: Icons.LifeBuoy,
};

export function DynamicIcon({ name, className }: { name: string; className?: string }) {
  const Icon = iconMap[name] || Icons.Box;
  return <Icon className={className} />;
}
