import type { ServiceWorkflowDef } from "./types";

const n = (
  id: string,
  label: string,
  story: string,
  brand?: string
): ServiceWorkflowDef["nodes"][number] => ({ id, label, story, brand });

/** Unique logo-centric workflows — Rolan is always the hub (rendered in canvas). */
export const SERVICE_WORKFLOWS: Record<string, ServiceWorkflowDef> = {
  workflow: {
    caption: "Trigger → Apps → Logic → Deliver",
    nodes: [
      n("zapier", "Zapier", "Zap fires → Rolan routes actions", "Zapier"),
      n("n8n", "n8n", "Self-hosted workflow executes", "n8n"),
      n("make", "Make", "Scenario modules sync data", "Make.com"),
      n("sheets", "Sheets", "Rows update in real time", "Google Sheets"),
      n("slack", "Slack", "Team notified instantly", "Slack"),
      n("gmail", "Gmail", "Confirmation email sent", "Gmail"),
    ],
    paths: [
      ["zapier", "n8n", "sheets", "slack"],
      ["make", "gmail", "sheets"],
      ["n8n", "slack", "gmail"],
    ],
    activities: [
      { title: "Workflow run #4821", meta: "0.8s · success" },
      { title: "Branch: VIP path", meta: "Filter matched" },
      { title: "3 apps updated", meta: "No errors" },
    ],
    metric: { label: "Runs today", value: "1,284", delta: "+18%" },
  },
  "ai-automation": {
    caption: "Data → AI → Decide → Act",
    nodes: [
      n("openai", "OpenAI", "Model generates a decision", "OpenAI"),
      n("claude", "Claude", "Document reasoned & extracted", "Claude"),
      n("gemini", "Gemini", "Multimodal insight produced", "Gemini"),
      n("n8n", "n8n", "AI node pushes to systems", "n8n"),
      n("hubspot", "HubSpot", "CRM fields enriched", "HubSpot"),
      n("slack", "Slack", "Insight shared with team", "Slack"),
    ],
    paths: [
      ["openai", "n8n", "hubspot"],
      ["claude", "n8n", "slack"],
      ["gemini", "openai", "hubspot"],
    ],
    activities: [
      { title: "Intent: billing", meta: "98% confidence" },
      { title: "Tool call complete", meta: "KB + CRM" },
      { title: "Action queued", meta: "Update deal" },
    ],
    metric: { label: "Auto-resolved", value: "73%", delta: "+9pts" },
  },
  business: {
    caption: "Request → Approve → Execute → Archive",
    nodes: [
      n("gmail", "Gmail", "Request received by inbox", "Gmail"),
      n("notion", "Notion", "Process checklist updated", "Notion"),
      n("clickup", "ClickUp", "Task assigned & tracked", "ClickUp"),
      n("drive", "Drive", "Docs archived securely", "Google Drive"),
      n("slack", "Slack", "Approvers notified", "Slack"),
      n("sheets", "Sheets", "Audit row appended", "Google Sheets"),
    ],
    paths: [
      ["gmail", "slack", "clickup"],
      ["notion", "drive", "sheets"],
      ["clickup", "slack", "gmail"],
    ],
    activities: [
      { title: "PO approved", meta: "Finance · 2m" },
      { title: "Vendor notified", meta: "Email sent" },
      { title: "Audit logged", meta: "Immutable" },
    ],
    metric: { label: "Cycle time", value: "2.1d", delta: "-64%" },
  },
  crm: {
    caption: "Lead → Qualify → Pipeline → Won",
    nodes: [
      n("hubspot", "HubSpot", "Lead lands in CRM", "HubSpot"),
      n("pipedrive", "Pipedrive", "Deal stage advances", "Pipedrive"),
      n("gmail", "Gmail", "Qualification email sent", "Gmail"),
      n("calendar", "Calendar", "Discovery call booked", "Google Calendar"),
      n("whatsapp", "WhatsApp", "Sales nudge delivered", "WhatsApp"),
      n("slack", "Slack", "Won deal celebration", "Slack"),
    ],
    paths: [
      ["hubspot", "gmail", "calendar"],
      ["pipedrive", "whatsapp", "slack"],
      ["hubspot", "pipedrive", "gmail"],
    ],
    activities: [
      { title: "Facebook lead in", meta: "Scored 82" },
      { title: "Owner assigned", meta: "Jordan · AE" },
      { title: "Deal won", meta: "$12.4k" },
    ],
    metric: { label: "Pipeline velocity", value: "4.2×", delta: "+31%" },
  },
  api: {
    caption: "Source → Transform → Sync → Monitor",
    nodes: [
      n("n8n", "n8n", "Webhook received & mapped", "n8n"),
      n("make", "Make", "Scenario transforms payload", "Make.com"),
      n("hubspot", "HubSpot", "Destination synced", "HubSpot"),
      n("sheets", "Sheets", "Mirror table updated", "Google Sheets"),
      n("slack", "Slack", "Ops alert if fail", "Slack"),
      n("salesforce", "Salesforce", "Object upserted", "Salesforce"),
    ],
    paths: [
      ["n8n", "hubspot", "sheets"],
      ["make", "salesforce", "slack"],
      ["n8n", "make", "hubspot"],
    ],
    activities: [
      { title: "Webhook 200", meta: "42ms" },
      { title: "14 fields mapped", meta: "Schema OK" },
      { title: "Retry budget healthy", meta: "0 fails" },
    ],
    metric: { label: "Sync latency", value: "118ms", delta: "p95" },
  },
  zapier: {
    caption: "Zap → Filter → Paths → Actions",
    nodes: [
      n("zapier", "Zapier", "Zap trigger fires", "Zapier"),
      n("gmail", "Gmail", "Email parsed", "Gmail"),
      n("sheets", "Sheets", "Row created", "Google Sheets"),
      n("hubspot", "HubSpot", "Contact upserted", "HubSpot"),
      n("slack", "Slack", "Channel pinged", "Slack"),
      n("calendar", "Calendar", "Event created", "Google Calendar"),
    ],
    paths: [
      ["zapier", "gmail", "sheets"],
      ["zapier", "hubspot", "slack"],
      ["zapier", "calendar", "gmail"],
    ],
    activities: [
      { title: "Zap ran", meta: "Gmail → Sheets" },
      { title: "Filter passed", meta: "Subject match" },
      { title: "3 steps done", meta: "0.9s" },
    ],
    metric: { label: "Zaps live", value: "86", delta: "stable" },
  },
  make: {
    caption: "Scenario · Modules · Router · Deliver",
    nodes: [
      n("make", "Make", "Scenario starts", "Make.com"),
      n("sheets", "Sheets", "Iterator batch loaded", "Google Sheets"),
      n("hubspot", "HubSpot", "Router → CRM path", "HubSpot"),
      n("whatsapp", "WhatsApp", "Template message sent", "WhatsApp"),
      n("drive", "Drive", "File archived", "Google Drive"),
      n("slack", "Slack", "Error handler idle", "Slack"),
    ],
    paths: [
      ["make", "sheets", "hubspot"],
      ["make", "whatsapp", "slack"],
      ["make", "drive", "sheets"],
    ],
    activities: [
      { title: "Iterator ×50", meta: "Batch OK" },
      { title: "Router Path B", meta: "Priority" },
      { title: "Clean run", meta: "No errors" },
    ],
    metric: { label: "Ops / month", value: "12.4k", delta: "used" },
  },
  n8n: {
    caption: "Webhook → Code → AI → Output",
    nodes: [
      n("n8n", "n8n", "Queue worker picks job", "n8n"),
      n("openai", "OpenAI", "AI node generates text", "OpenAI"),
      n("hubspot", "HubSpot", "CRM write-back", "HubSpot"),
      n("telegram", "Telegram", "Ops bot notified", "Telegram"),
      n("sheets", "Sheets", "Log sheet appended", "Google Sheets"),
      n("gmail", "Gmail", "Customer reply sent", "Gmail"),
    ],
    paths: [
      ["n8n", "openai", "hubspot"],
      ["n8n", "telegram", "sheets"],
      ["n8n", "openai", "gmail"],
    ],
    activities: [
      { title: "Self-hosted run", meta: "Worker-2" },
      { title: "JS transform", meta: "42ms" },
      { title: "Postgres insert ×12", meta: "OK" },
    ],
    metric: { label: "Workflows", value: "64", delta: "prod" },
  },
  openai: {
    caption: "Prompt → GPT → Tools → Reply",
    nodes: [
      n("openai", "OpenAI", "Completion streaming", "OpenAI"),
      n("n8n", "n8n", "Tool orchestration", "n8n"),
      n("zendesk", "Zendesk", "Ticket draft ready", "Zendesk"),
      n("slack", "Slack", "Human review ping", "Slack"),
      n("drive", "Drive", "Context docs loaded", "Google Drive"),
      n("gmail", "Gmail", "Reply delivered", "Gmail"),
    ],
    paths: [
      ["openai", "n8n", "zendesk"],
      ["openai", "drive", "gmail"],
      ["openai", "slack", "n8n"],
    ],
    activities: [
      { title: "Tokens 1,842", meta: "gpt-4.1" },
      { title: "Tool: search", meta: "KB hit" },
      { title: "Streamed reply", meta: "1.2s TTFB" },
    ],
    metric: { label: "Eval score", value: "4.8★", delta: "avg" },
  },
  claude: {
    caption: "Document → Claude → Extract → Route",
    nodes: [
      n("claude", "Claude", "Long-context reasoning", "Claude"),
      n("drive", "Drive", "Source PDF loaded", "Google Drive"),
      n("notion", "Notion", "Summary published", "Notion"),
      n("hubspot", "HubSpot", "Entities written", "HubSpot"),
      n("slack", "Slack", "Legal queue alert", "Slack"),
      n("n8n", "n8n", "Pipeline orchestration", "n8n"),
    ],
    paths: [
      ["drive", "claude", "notion"],
      ["claude", "hubspot", "slack"],
      ["claude", "n8n", "hubspot"],
    ],
    activities: [
      { title: "PDF 28 pages", meta: "Parsed" },
      { title: "14 fields extracted", meta: "High conf." },
      { title: "Routed to legal", meta: "Priority" },
    ],
    metric: { label: "Accuracy", value: "96%", delta: "spot" },
  },
  gemini: {
    caption: "Vision + Text → Gemini → Insight",
    nodes: [
      n("gemini", "Gemini", "Multimodal analysis", "Gemini"),
      n("drive", "Drive", "Image assets loaded", "Google Drive"),
      n("sheets", "Sheets", "Findings logged", "Google Sheets"),
      n("slack", "Slack", "QA alert posted", "Slack"),
      n("n8n", "n8n", "Workflow continues", "n8n"),
      n("gmail", "Gmail", "Report emailed", "Gmail"),
    ],
    paths: [
      ["drive", "gemini", "sheets"],
      ["gemini", "slack", "n8n"],
      ["gemini", "gmail", "sheets"],
    ],
    activities: [
      { title: "Photo + note", meta: "Multimodal" },
      { title: "Defect flagged", meta: "High sev." },
      { title: "Ticket opened", meta: "QA board" },
    ],
    metric: { label: "Latency", value: "840ms", delta: "median" },
  },
  whatsapp: {
    caption: "Message → Bot → CRM → Handoff",
    nodes: [
      n("whatsapp", "WhatsApp", "Customer message in", "WhatsApp"),
      n("openai", "OpenAI", "Intent detected", "OpenAI"),
      n("hubspot", "HubSpot", "Timeline logged", "HubSpot"),
      n("make", "Make", "Automation routes reply", "Make.com"),
      n("sheets", "Sheets", "Order row found", "Google Sheets"),
      n("slack", "Slack", "Human handoff ready", "Slack"),
    ],
    paths: [
      ["whatsapp", "openai", "hubspot"],
      ["whatsapp", "make", "sheets"],
      ["whatsapp", "openai", "slack"],
    ],
    activities: [
      { title: "Order status asked", meta: "Template" },
      { title: "Auto-reply sent", meta: "ETA 2 days" },
      { title: "Logged to CRM", meta: "Contact" },
    ],
    metric: { label: "Auto-handled", value: "85%", delta: "chats" },
  },
  email: {
    caption: "Inbox → Classify → Sequence → CRM",
    nodes: [
      n("gmail", "Gmail", "Inbox event captured", "Gmail"),
      n("openai", "OpenAI", "Email classified", "OpenAI"),
      n("hubspot", "HubSpot", "Sequence enrolled", "HubSpot"),
      n("zapier", "Zapier", "Follow-up Zap runs", "Zapier"),
      n("calendar", "Calendar", "Meeting proposed", "Google Calendar"),
      n("slack", "Slack", "Sales notified", "Slack"),
    ],
    paths: [
      ["gmail", "openai", "hubspot"],
      ["gmail", "zapier", "calendar"],
      ["openai", "hubspot", "slack"],
    ],
    activities: [
      { title: "Intent: billing", meta: "AI tag" },
      { title: "Sequence started", meta: "3 touches" },
      { title: "Stage: Negotiation", meta: "Updated" },
    ],
    metric: { label: "Open rate", value: "48%", delta: "+6pts" },
  },
  leads: {
    caption: "Capture → Enrich → Score → Route",
    nodes: [
      n("hubspot", "HubSpot", "Lead captured", "HubSpot"),
      n("pipedrive", "Pipedrive", "Deal created", "Pipedrive"),
      n("sheets", "Sheets", "Enrichment sheet sync", "Google Sheets"),
      n("openai", "OpenAI", "Lead scored", "OpenAI"),
      n("gmail", "Gmail", "Intro email sent", "Gmail"),
      n("whatsapp", "WhatsApp", "Instant follow-up", "WhatsApp"),
    ],
    paths: [
      ["hubspot", "openai", "pipedrive"],
      ["hubspot", "gmail", "whatsapp"],
      ["sheets", "openai", "hubspot"],
    ],
    activities: [
      { title: "LinkedIn form", meta: "Ingested" },
      { title: "Firmographics filled", meta: "Enrich" },
      { title: "Routed West AE", meta: "Score 88" },
    ],
    metric: { label: "Qualified / day", value: "142", delta: "+3×" },
  },
  appointments: {
    caption: "Request → Slot → Book → Remind",
    nodes: [
      n("calendly", "Calendly", "Slot selected", "Calendly"),
      n("calendar", "Calendar", "Event created", "Google Calendar"),
      n("meet", "Meet", "Video link ready", "Google Meet"),
      n("gmail", "Gmail", "Invite emailed", "Gmail"),
      n("whatsapp", "WhatsApp", "SMS/WA reminder", "WhatsApp"),
      n("hubspot", "HubSpot", "Meeting logged", "HubSpot"),
    ],
    paths: [
      ["calendly", "calendar", "meet"],
      ["calendly", "gmail", "whatsapp"],
      ["calendar", "hubspot", "gmail"],
    ],
    activities: [
      { title: "Thu 2:30 held", meta: "Pacific" },
      { title: "Meet link created", meta: "Ready" },
      { title: "T-24h reminder", meta: "Queued" },
    ],
    metric: { label: "No-show rate", value: "8%", delta: "-22pts" },
  },
  chatbots: {
    caption: "Visitor → Bot → Knowledge → Escalate",
    nodes: [
      n("openai", "OpenAI", "Bot replies naturally", "OpenAI"),
      n("zendesk", "Zendesk", "Ticket opened if needed", "Zendesk"),
      n("notion", "Notion", "KB article cited", "Notion"),
      n("whatsapp", "WhatsApp", "Channel continued", "WhatsApp"),
      n("hubspot", "HubSpot", "Visitor identified", "HubSpot"),
      n("slack", "Slack", "Agent handoff", "Slack"),
    ],
    paths: [
      ["openai", "notion", "hubspot"],
      ["openai", "zendesk", "slack"],
      ["whatsapp", "openai", "notion"],
    ],
    activities: [
      { title: "FAQ matched", meta: "Shipping" },
      { title: "Doc #204 cited", meta: "KB" },
      { title: "Handoff ready", meta: "CS queue" },
    ],
    metric: { label: "Containment", value: "71%", delta: "+12pts" },
  },
  voice: {
    caption: "Call → Voice AI → Intent → Transfer",
    nodes: [
      n("openai", "OpenAI", "Speech intent parsed", "OpenAI"),
      n("twilio", "Twilio", "Media stream live", "Twilio"),
      n("3cx", "3CX", "Warm transfer to agent", "3CX"),
      n("hubspot", "HubSpot", "Call logged", "HubSpot"),
      n("calendar", "Calendar", "Appointment set", "Google Calendar"),
      n("slack", "Slack", "Supervisor alert", "Slack"),
    ],
    paths: [
      ["twilio", "openai", "3cx"],
      ["openai", "hubspot", "calendar"],
      ["3cx", "hubspot", "slack"],
    ],
    activities: [
      { title: "Natural TTS greeting", meta: "Played" },
      { title: "Intent: booking", meta: "0.91" },
      { title: "Ext 204 transfer", meta: "Warm" },
    ],
    metric: { label: "Tier-1 auto", value: "68%", delta: "calls" },
  },
  support: {
    caption: "Customer → AI → Knowledge → Human",
    nodes: [
      n("zendesk", "Zendesk", "Ticket received", "Zendesk"),
      n("openai", "OpenAI", "AI drafts reply", "OpenAI"),
      n("notion", "Notion", "KB lights up", "Notion"),
      n("slack", "Slack", "L2 escalation", "Slack"),
      n("gmail", "Gmail", "Resolution emailed", "Gmail"),
      n("hubspot", "HubSpot", "CSAT logged", "HubSpot"),
    ],
    paths: [
      ["zendesk", "openai", "notion"],
      ["openai", "slack", "zendesk"],
      ["notion", "gmail", "hubspot"],
    ],
    activities: [
      { title: "Ticket triaged", meta: "Med priority" },
      { title: "Draft ready", meta: "Review" },
      { title: "Resolved ✓", meta: "CSAT 5★" },
    ],
    metric: { label: "First response", value: "<2m", delta: "median" },
  },
  internal: {
    caption: "HR · Finance · Ops · Alerts",
    nodes: [
      n("notion", "Notion", "Policy workspace", "Notion"),
      n("clickup", "ClickUp", "Internal tasks", "ClickUp"),
      n("gmail", "Gmail", "Approvals inbox", "Gmail"),
      n("sheets", "Sheets", "Finance tracker", "Google Sheets"),
      n("slack", "Slack", "Ops channel", "Slack"),
      n("drive", "Drive", "Shared archives", "Google Drive"),
    ],
    paths: [
      ["gmail", "clickup", "slack"],
      ["notion", "drive", "sheets"],
      ["sheets", "slack", "gmail"],
    ],
    activities: [
      { title: "Onboarding Day 1", meta: "Done" },
      { title: "Expense $340", meta: "Approved" },
      { title: "SLA ping", meta: "Ops" },
    ],
    metric: { label: "Hrs saved / wk", value: "38", delta: "team" },
  },
  data: {
    caption: "Extract → Clean → Load → Warehouse",
    nodes: [
      n("n8n", "n8n", "ETL job running", "n8n"),
      n("sheets", "Sheets", "Staging cleaned", "Google Sheets"),
      n("drive", "Drive", "Exports archived", "Google Drive"),
      n("hubspot", "HubSpot", "CRM mirror sync", "HubSpot"),
      n("airtable", "Airtable", "Ops base updated", "Airtable"),
      n("slack", "Slack", "Freshness alert", "Slack"),
    ],
    paths: [
      ["n8n", "sheets", "hubspot"],
      ["n8n", "airtable", "slack"],
      ["drive", "n8n", "sheets"],
    ],
    activities: [
      { title: "ETL #291", meta: "Running" },
      { title: "Dupes removed", meta: "1,204" },
      { title: "Warehouse sync", meta: "OK" },
    ],
    metric: { label: "Freshness", value: "4m", delta: "lag" },
  },
  dashboards: {
    caption: "Sources → Metrics → Charts → Alerts",
    nodes: [
      n("sheets", "Sheets", "Metric source live", "Google Sheets"),
      n("hubspot", "HubSpot", "Pipeline KPIs", "HubSpot"),
      n("n8n", "n8n", "Refresh every 5m", "n8n"),
      n("slack", "Slack", "Threshold alert", "Slack"),
      n("notion", "Notion", "Exec summary", "Notion"),
      n("gmail", "Gmail", "Digest emailed", "Gmail"),
    ],
    paths: [
      ["sheets", "n8n", "hubspot"],
      ["hubspot", "slack", "notion"],
      ["n8n", "gmail", "sheets"],
    ],
    activities: [
      { title: "Board refreshed", meta: "5m cadence" },
      { title: "Revenue +12%", meta: "WoW" },
      { title: "ASA > 45s", meta: "Queue B" },
    ],
    metric: { label: "Live widgets", value: "24", delta: "board" },
  },
  web: {
    caption: "Browse → Extract → Validate → Write",
    nodes: [
      n("n8n", "n8n", "Headless session", "n8n"),
      n("sheets", "Sheets", "Rows appended", "Google Sheets"),
      n("drive", "Drive", "Screenshots saved", "Google Drive"),
      n("airtable", "Airtable", "Validated records", "Airtable"),
      n("slack", "Slack", "Job complete ping", "Slack"),
      n("gmail", "Gmail", "Report mailed", "Gmail"),
    ],
    paths: [
      ["n8n", "sheets", "airtable"],
      ["n8n", "drive", "slack"],
      ["sheets", "gmail", "slack"],
    ],
    activities: [
      { title: "Chrome session", meta: "Started" },
      { title: "48 rows scraped", meta: "Schema OK" },
      { title: "Sheet updated", meta: "Append" },
    ],
    metric: { label: "Success rate", value: "99.1%", delta: "jobs" },
  },
  consulting: {
    caption: "Audit → Roadmap → Pilot → Scale",
    nodes: [
      n("notion", "Notion", "Audit workspace", "Notion"),
      n("sheets", "Sheets", "ROI model", "Google Sheets"),
      n("calendar", "Calendar", "Workshop booked", "Google Calendar"),
      n("slack", "Slack", "Stakeholder sync", "Slack"),
      n("drive", "Drive", "Deliverables folder", "Google Drive"),
      n("gmail", "Gmail", "Proposal sent", "Gmail"),
    ],
    paths: [
      ["notion", "sheets", "gmail"],
      ["calendar", "slack", "drive"],
      ["sheets", "notion", "gmail"],
    ],
    activities: [
      { title: "12 processes mapped", meta: "Workshop" },
      { title: "ROI scenarios ×3", meta: "Ready" },
      { title: "Pilot #1 scoped", meta: "2 weeks" },
    ],
    metric: { label: "Projected ROI", value: "340%", delta: "Yr1" },
  },

  "3cx": {
    caption: "Call → SIP → IVR → Queue → Agent → CRM → Analytics",
    nodes: [
      n("sip", "SIP", "Trunk receives call", "Twilio"),
      n("3cx", "3CX", "PBX routes the session", "3CX"),
      n("hubspot", "CRM", "Screen-pop + log", "HubSpot"),
      n("agent", "Agent", "Available agent answers", undefined),
      n("slack", "Alert", "Supervisor whisper", "Slack"),
      n("sheets", "Analytics", "CDR metrics update", "Google Sheets"),
    ],
    paths: [
      ["sip", "3cx", "hubspot"],
      ["3cx", "agent", "sheets"],
      ["3cx", "hubspot", "slack"],
    ],
    activities: [
      { title: "IVR option 2", meta: "Support" },
      { title: "Queue wait 12s", meta: "Skills match" },
      { title: "Call recorded", meta: "CRM linked" },
    ],
    metric: { label: "Active calls", value: "24", delta: "live" },
  },
  vicidial: {
    caption: "Lead → Campaign → Dialer → Agent → CRM → Report",
    nodes: [
      n("vicidial", "VICIdial", "Predictive pace adapts", "VICIdial"),
      n("hubspot", "CRM", "Disposition synced", "HubSpot"),
      n("salesforce", "Salesforce", "Opportunity updated", "Salesforce"),
      n("sheets", "Reports", "Live campaign stats", "Google Sheets"),
      n("twilio", "SIP", "Carrier channels up", "Twilio"),
      n("slack", "Ops", "Drop % alert", "Slack"),
    ],
    paths: [
      ["vicidial", "twilio", "hubspot"],
      ["vicidial", "salesforce", "sheets"],
      ["vicidial", "hubspot", "slack"],
    ],
    activities: [
      { title: "Hopper 2,400", meta: "Loaded" },
      { title: "Connect 31%", meta: "Predictive" },
      { title: "Dispo: SALE", meta: "Agent 6666" },
    ],
    metric: { label: "Talk / agent", value: "48m", delta: "today" },
  },
  freepbx: {
    caption: "Trunk → Extensions → Routes → Apps",
    nodes: [
      n("freepbx", "FreePBX", "Admin dashboard healthy", "FreePBX"),
      n("asterisk", "Asterisk", "Channels online", "Asterisk"),
      n("twilio", "SIP", "Primary trunk up", "Twilio"),
      n("hubspot", "CRM", "Click-to-dial linked", "HubSpot"),
      n("slack", "Alerts", "Failover tested", "Slack"),
      n("sheets", "CDR", "Reports exported", "Google Sheets"),
    ],
    paths: [
      ["twilio", "freepbx", "asterisk"],
      ["freepbx", "hubspot", "sheets"],
      ["asterisk", "slack", "freepbx"],
    ],
    activities: [
      { title: "Trunk registered", meta: "Primary" },
      { title: "40 extensions", meta: "Live" },
      { title: "Failover OK", meta: "Secondary" },
    ],
    metric: { label: "Uptime", value: "99.98%", delta: "30d" },
  },
  asterisk: {
    caption: "Dialplan → Channels → Apps → CDR",
    nodes: [
      n("asterisk", "Asterisk", "Dialplan matched", "Asterisk"),
      n("freepbx", "FreePBX", "GUI config applied", "FreePBX"),
      n("twilio", "SIP", "PJSIP channel up", "Twilio"),
      n("n8n", "n8n", "AMI event → automation", "n8n"),
      n("sheets", "CDR", "Call detail written", "Google Sheets"),
      n("slack", "Ops", "Channel peak alert", "Slack"),
    ],
    paths: [
      ["asterisk", "twilio", "freepbx"],
      ["asterisk", "n8n", "sheets"],
      ["asterisk", "slack", "sheets"],
    ],
    activities: [
      { title: "from-internal", meta: "Context" },
      { title: "PJSIP/204", meta: "Up" },
      { title: "CDR → MySQL", meta: "OK" },
    ],
    metric: { label: "Channels", value: "86", delta: "peak" },
  },
  pbx: {
    caption: "Design → Deploy → Provision → Monitor",
    nodes: [
      n("3cx", "3CX", "Cloud PBX deployed", "3CX"),
      n("freepbx", "FreePBX", "Alt stack ready", "FreePBX"),
      n("twilio", "SIP", "Dual trunks", "Twilio"),
      n("hubspot", "CRM", "Users synced", "HubSpot"),
      n("slack", "Monitor", "Health green", "Slack"),
      n("sheets", "Report", "Site dashboard", "Google Sheets"),
    ],
    paths: [
      ["3cx", "twilio", "hubspot"],
      ["freepbx", "twilio", "sheets"],
      ["3cx", "slack", "sheets"],
    ],
    activities: [
      { title: "HA pair signed", meta: "Arch" },
      { title: "Cluster live", meta: "Cloud" },
      { title: "Health checks", meta: "Green" },
    ],
    metric: { label: "Sites", value: "6", delta: "unified" },
  },
  voip: {
    caption: "SIP → QoS → Softphone → Failover",
    nodes: [
      n("twilio", "SIP", "Business trunks", "Twilio"),
      n("3cx", "3CX", "Softphones registered", "3CX"),
      n("vicidial", "Dialer", "Outbound ready", "VICIdial"),
      n("slack", "NOC", "MOS monitored", "Slack"),
      n("sheets", "QoS", "Jitter logged", "Google Sheets"),
      n("hubspot", "CRM", "Click-to-dial", "HubSpot"),
    ],
    paths: [
      ["twilio", "3cx", "hubspot"],
      ["twilio", "vicidial", "sheets"],
      ["3cx", "slack", "sheets"],
    ],
    activities: [
      { title: "MOS 4.3", meta: "Excellent" },
      { title: "Jitter 18ms", meta: "OK" },
      { title: "Failover idle", meta: "Standby" },
    ],
    metric: { label: "Completion", value: "99.99%", delta: "SLA" },
  },
  recording: {
    caption: "Call → Capture → Encrypt → Search",
    nodes: [
      n("3cx", "3CX", "Recording started", "3CX"),
      n("hubspot", "CRM", "Call linked", "HubSpot"),
      n("drive", "Vault", "Encrypted archive", "Google Drive"),
      n("salesforce", "SFDC", "Activity attached", "Salesforce"),
      n("slack", "Compliance", "Retention OK", "Slack"),
      n("sheets", "Index", "Searchable tags", "Google Sheets"),
    ],
    paths: [
      ["3cx", "drive", "hubspot"],
      ["3cx", "salesforce", "sheets"],
      ["drive", "slack", "sheets"],
    ],
    activities: [
      { title: "Stereo capture", meta: "Live" },
      { title: "AES vault", meta: "Stored" },
      { title: "CRM indexed", meta: "Linked" },
    ],
    metric: { label: "Retention", value: "7 yrs", delta: "policy" },
  },
  routing: {
    caption: "DID → Rules → Skills → Agent",
    nodes: [
      n("3cx", "3CX", "Skills routing", "3CX"),
      n("hubspot", "CRM", "Caller context", "HubSpot"),
      n("twilio", "DID", "Number matched", "Twilio"),
      n("slack", "Team", "Overflow alert", "Slack"),
      n("calendar", "Hours", "Business hours", "Google Calendar"),
      n("sheets", "Rules", "Route table", "Google Sheets"),
    ],
    paths: [
      ["twilio", "3cx", "hubspot"],
      ["calendar", "3cx", "slack"],
      ["sheets", "3cx", "hubspot"],
    ],
    activities: [
      { title: "Hours match", meta: "Open" },
      { title: "Skill: billing", meta: "P1" },
      { title: "Ringing 118", meta: "Available" },
    ],
    metric: { label: "Wrong dept", value: "-30%", delta: "xfers" },
  },
  ivr: {
    caption: "Welcome → Menu → Input → Route",
    nodes: [
      n("3cx", "3CX", "IVR menu active", "3CX"),
      n("openai", "NLU", "Spoken intent", "OpenAI"),
      n("hubspot", "CRM", "Caller known", "HubSpot"),
      n("twilio", "Trunk", "Audio path", "Twilio"),
      n("slack", "Ops", "Menu abandon", "Slack"),
      n("sheets", "Stats", "Option analytics", "Google Sheets"),
    ],
    paths: [
      ["twilio", "3cx", "openai"],
      ["3cx", "hubspot", "sheets"],
      ["openai", "3cx", "slack"],
    ],
    activities: [
      { title: "Language EN", meta: "Selected" },
      { title: "Option 3", meta: "Scheduling" },
      { title: "Clinic queue", meta: "Forwarded" },
    ],
    metric: { label: "Self-serve", value: "54%", delta: "exits" },
  },
  sip: {
    caption: "Carrier → Trunk → PBX → Endpoints",
    nodes: [
      n("twilio", "Carrier", "SIP registered", "Twilio"),
      n("3cx", "PBX", "Endpoints online", "3CX"),
      n("freepbx", "FreePBX", "Alt route", "FreePBX"),
      n("hubspot", "CRM", "Click-to-dial", "HubSpot"),
      n("slack", "NOC", "Reg flap alert", "Slack"),
      n("sheets", "Codec", "G.722 negotiated", "Google Sheets"),
    ],
    paths: [
      ["twilio", "3cx", "hubspot"],
      ["twilio", "freepbx", "sheets"],
      ["3cx", "slack", "sheets"],
    ],
    activities: [
      { title: "Registration OK", meta: "Primary" },
      { title: "Codec G.722", meta: "HD" },
      { title: "118 / 120 online", meta: "Phones" },
    ],
    metric: { label: "Channels", value: "64", delta: "conc." },
  },
  queue: {
    caption: "Caller → Strategy → Wait → Agent",
    nodes: [
      n("3cx", "Queue", "Priority strategy", "3CX"),
      n("hubspot", "CRM", "VIP tag applied", "HubSpot"),
      n("twilio", "Inbound", "Caller waiting", "Twilio"),
      n("slack", "Floor", "Callback offered", "Slack"),
      n("sheets", "SLA", "ASA tracked", "Google Sheets"),
      n("whatsapp", "Callback", "WA callback link", "WhatsApp"),
    ],
    paths: [
      ["twilio", "3cx", "hubspot"],
      ["3cx", "whatsapp", "slack"],
      ["3cx", "sheets", "hubspot"],
    ],
    activities: [
      { title: "VIP bump", meta: "Priority" },
      { title: "Position 4", meta: "Callback" },
      { title: "ASA 18s", meta: "Connected" },
    ],
    metric: { label: "Abandon", value: "4.2%", delta: "-40%" },
  },
  predictive: {
    caption: "List → Pace → Connect → Disposition",
    nodes: [
      n("vicidial", "Dialer", "Dial level adapts", "VICIdial"),
      n("hubspot", "CRM", "Talking = logged", "HubSpot"),
      n("twilio", "SIP", "Outbound channels", "Twilio"),
      n("sheets", "Pace", "Drop % compliant", "Google Sheets"),
      n("slack", "Floor", "Agents talking", "Slack"),
      n("salesforce", "SFDC", "Dispo synced", "Salesforce"),
    ],
    paths: [
      ["vicidial", "twilio", "hubspot"],
      ["vicidial", "sheets", "slack"],
      ["vicidial", "salesforce", "hubspot"],
    ],
    activities: [
      { title: "Dial level 2.6", meta: "Adaptive" },
      { title: "Drop 0.1%", meta: "Compliant" },
      { title: "96 talking", meta: "Live" },
    ],
    metric: { label: "Connects / hr", value: "38", delta: "/agent" },
  },
  progressive: {
    caption: "Preview → Dial → Talk → Log",
    nodes: [
      n("vicidial", "Progressive", "Agent preview window", "VICIdial"),
      n("hubspot", "CRM", "Lead card open", "HubSpot"),
      n("twilio", "Dial", "Outbound placed", "Twilio"),
      n("gmail", "Follow-up", "Email after call", "Gmail"),
      n("sheets", "Log", "Notes synced", "Google Sheets"),
      n("slack", "Coach", "Whisper available", "Slack"),
    ],
    paths: [
      ["vicidial", "hubspot", "twilio"],
      ["vicidial", "gmail", "sheets"],
      ["hubspot", "slack", "sheets"],
    ],
    activities: [
      { title: "Preview 8s", meta: "Window" },
      { title: "Agent accepted", meta: "Dial" },
      { title: "CRM notes", meta: "Synced" },
    ],
    metric: { label: "DNC", value: "100%", delta: "safe" },
  },
  inbound: {
    caption: "DID → Screen-pop → Agent → Wrap",
    nodes: [
      n("3cx", "Inbound", "Call answered", "3CX"),
      n("hubspot", "Screen-pop", "Contact loaded", "HubSpot"),
      n("zendesk", "Ticket", "Case context", "Zendesk"),
      n("slack", "Team", "Warm transfer", "Slack"),
      n("gmail", "Wrap", "Summary mailed", "Gmail"),
      n("sheets", "ASA", "Stats update", "Google Sheets"),
    ],
    paths: [
      ["3cx", "hubspot", "zendesk"],
      ["3cx", "slack", "gmail"],
      ["hubspot", "sheets", "gmail"],
    ],
    activities: [
      { title: "Caller matched", meta: "CRM" },
      { title: "Last 5 tickets", meta: "Loaded" },
      { title: "Resolved", meta: "Dispo" },
    ],
    metric: { label: "ASA", value: "22s", delta: "today" },
  },
  outbound: {
    caption: "Campaign → Dial → Pitch → Close",
    nodes: [
      n("vicidial", "Campaign", "Script v3 loaded", "VICIdial"),
      n("hubspot", "CRM", "Interest detected", "HubSpot"),
      n("pipedrive", "Pipeline", "Deal created", "Pipedrive"),
      n("gmail", "Follow-up", "Proposal sent", "Gmail"),
      n("whatsapp", "Nurture", "WA sequence", "WhatsApp"),
      n("sheets", "Conv.", "Conversion up", "Google Sheets"),
    ],
    paths: [
      ["vicidial", "hubspot", "pipedrive"],
      ["vicidial", "gmail", "whatsapp"],
      ["pipedrive", "sheets", "gmail"],
    ],
    activities: [
      { title: "Compliance OK", meta: "Script" },
      { title: "AI assist hint", meta: "Upsell" },
      { title: "Deal $890", meta: "Created" },
    ],
    metric: { label: "Conversion", value: "2.8×", delta: "vs man." },
  },
  "cloud-pbx": {
    caption: "Sites → Cloud PBX → Users → Reporting",
    nodes: [
      n("3cx", "Cloud", "Multi-site PBX", "3CX"),
      n("twilio", "Trunks", "Regional SIP", "Twilio"),
      n("hubspot", "Users", "Directory sync", "HubSpot"),
      n("slack", "Ops", "Central alerts", "Slack"),
      n("sheets", "Reports", "Exec board", "Google Sheets"),
      n("meet", "Video", "Meetings included", "Google Meet"),
    ],
    paths: [
      ["3cx", "twilio", "hubspot"],
      ["3cx", "sheets", "slack"],
      ["3cx", "meet", "hubspot"],
    ],
    activities: [
      { title: "12 sites linked", meta: "VPN+SBC" },
      { title: "Shared queues", meta: "Central" },
      { title: "Exec dashboard", meta: "Live" },
    ],
    metric: { label: "Cost save", value: "35%", delta: "YoY" },
  },
  analytics: {
    caption: "CDR → Metrics → Wallboard → Insights",
    nodes: [
      n("3cx", "CDR", "Call data flowing", "3CX"),
      n("sheets", "Metrics", "AHT / ASA live", "Google Sheets"),
      n("hubspot", "Revenue", "Attribution", "HubSpot"),
      n("slack", "Coach", "Agent alert", "Slack"),
      n("notion", "Insights", "Weekly brief", "Notion"),
      n("n8n", "ETL", "Refresh cadence", "n8n"),
    ],
    paths: [
      ["3cx", "n8n", "sheets"],
      ["sheets", "hubspot", "notion"],
      ["3cx", "slack", "sheets"],
    ],
    activities: [
      { title: "AHT -14s", meta: "Trend" },
      { title: "SLA 98%", meta: "Queue A" },
      { title: "Coach: 204", meta: "Alert" },
    ],
    metric: { label: "Abandon", value: "3.1%", delta: "-1.4" },
  },
  "crm-int": {
    caption: "Call → Screen-pop → Log → Disposition",
    nodes: [
      n("3cx", "PBX", "Inbound ring", "3CX"),
      n("hubspot", "HubSpot", "Screen-pop", "HubSpot"),
      n("salesforce", "Salesforce", "Auto activity", "Salesforce"),
      n("pipedrive", "Pipedrive", "Deal touch", "Pipedrive"),
      n("slack", "Sales", "Missed call ping", "Slack"),
      n("gmail", "Email", "Follow-up draft", "Gmail"),
    ],
    paths: [
      ["3cx", "hubspot", "gmail"],
      ["3cx", "salesforce", "slack"],
      ["3cx", "pipedrive", "hubspot"],
    ],
    activities: [
      { title: "Contact matched", meta: "HubSpot" },
      { title: "0-click log", meta: "Auto" },
      { title: "Stage advanced", meta: "Qualified" },
    ],
    metric: { label: "Logged", value: "100%", delta: "auto" },
  },
  autodialer: {
    caption: "List → Auto-dial → AMD → Agent",
    nodes: [
      n("vicidial", "Auto-dial", "Retry schedule", "VICIdial"),
      n("twilio", "AMD", "Human detected", "Twilio"),
      n("hubspot", "CRM", "Agent bridged", "HubSpot"),
      n("sheets", "DNC", "Filter applied", "Google Sheets"),
      n("slack", "Floor", "Pace OK", "Slack"),
      n("gmail", "Follow-up", "No-answer email", "Gmail"),
    ],
    paths: [
      ["vicidial", "twilio", "hubspot"],
      ["vicidial", "sheets", "slack"],
      ["hubspot", "gmail", "sheets"],
    ],
    activities: [
      { title: "Max retries 3", meta: "Set" },
      { title: "AMD pass", meta: "Human" },
      { title: "Bridge 0.8s", meta: "Agent" },
    ],
    metric: { label: "DNC filter", value: "100%", delta: "safe" },
  },
  "agent-dash": {
    caption: "Presence → Stats → Scripts → Actions",
    nodes: [
      n("3cx", "Presence", "Available", "3CX"),
      n("hubspot", "Scripts", "Next-best action", "HubSpot"),
      n("sheets", "Stats", "Calls today 47", "Google Sheets"),
      n("slack", "Coach", "Tip delivered", "Slack"),
      n("notion", "Playbook", "Script v3", "Notion"),
      n("gmail", "Follow", "Task created", "Gmail"),
    ],
    paths: [
      ["3cx", "hubspot", "sheets"],
      ["3cx", "notion", "slack"],
      ["hubspot", "gmail", "sheets"],
    ],
    activities: [
      { title: "Agent 118", meta: "Available" },
      { title: "AHT 3:12", meta: "47 calls" },
      { title: "Upsell hint", meta: "NBA" },
    ],
    metric: { label: "Occupancy", value: "81%", delta: "tgt 85" },
  },
  remote: {
    caption: "Home → VPN → Softphone → QA",
    nodes: [
      n("3cx", "Softphone", "WebRTC registered", "3CX"),
      n("hubspot", "CRM", "Home agent ready", "HubSpot"),
      n("slack", "QA", "Whisper coaching", "Slack"),
      n("meet", "Brief", "Standup huddle", "Google Meet"),
      n("sheets", "QA", "Scorecards", "Google Sheets"),
      n("gmail", "HR", "Remote kit sent", "Gmail"),
    ],
    paths: [
      ["3cx", "hubspot", "slack"],
      ["3cx", "meet", "sheets"],
      ["hubspot", "gmail", "slack"],
    ],
    activities: [
      { title: "Tunnel up", meta: "Secure" },
      { title: "WebRTC OK", meta: "Reg" },
      { title: "Whisper live", meta: "Coach" },
    ],
    metric: { label: "Remote online", value: "92", delta: "agents" },
  },
};

export function getServiceWorkflow(serviceId: string): ServiceWorkflowDef {
  return (
    SERVICE_WORKFLOWS[serviceId] ?? {
      caption: "Connect → Automate → Deliver",
      nodes: [
        n("n8n", "n8n", "Workflow engine", "n8n"),
        n("hubspot", "CRM", "Customer data", "HubSpot"),
        n("slack", "Slack", "Team alerts", "Slack"),
        n("gmail", "Gmail", "Notifications", "Gmail"),
        n("sheets", "Sheets", "Records", "Google Sheets"),
        n("openai", "AI", "Intelligence", "OpenAI"),
      ],
      paths: [
        ["n8n", "hubspot", "slack"],
        ["openai", "n8n", "gmail"],
        ["sheets", "n8n", "hubspot"],
      ],
      activities: [
        { title: "Automation live", meta: "Rolan" },
        { title: "Sync OK", meta: "All systems" },
      ],
      metric: { label: "Status", value: "Live", delta: "demo" },
    }
  );
}
