import type { ServiceWorkflowDef } from "./types";

const edge = (from: string, to: string) => ({ from, to });

/** Unique interactive workflow story per service page. */
export const SERVICE_WORKFLOWS: Record<string, ServiceWorkflowDef> = {
  workflow: {
    layout: "flow",
    accent: "blue",
    caption: "Trigger → Transform → Route → Notify",
    nodes: [
      { id: "t", label: "Trigger", icon: "Zap", status: "done" },
      { id: "l", label: "Logic", icon: "GitBranch", status: "active" },
      { id: "a", label: "Apps", icon: "Plug", status: "idle" },
      { id: "n", label: "Notify", icon: "Bell", status: "idle" },
    ],
    edges: [edge("t", "l"), edge("l", "a"), edge("a", "n")],
    activities: [
      { title: "Form submitted", meta: "Webhooks · 0.4s", tone: "info" },
      { title: "Branch matched", meta: "VIP lead path", tone: "ok" },
      { title: "Slack + CRM synced", meta: "2 actions", tone: "ok" },
    ],
    metric: { label: "Runs today", value: "1,284", delta: "+18%" },
  },
  "ai-automation": {
    layout: "hub",
    accent: "violet",
    caption: "Data → Model → Decision → Action",
    nodes: [
      { id: "d", label: "Data", icon: "Database", status: "done" },
      { id: "m", label: "AI Model", icon: "Brain", status: "active" },
      { id: "c", label: "Decide", icon: "Sparkles", status: "idle" },
      { id: "x", label: "Act", icon: "Rocket", status: "idle" },
    ],
    edges: [edge("d", "m"), edge("m", "c"), edge("c", "x")],
    activities: [
      { title: "Intent classified", meta: "98% confidence", tone: "ok" },
      { title: "Policy check passed", meta: "Guardrails", tone: "info" },
      { title: "Action queued", meta: "CRM update", tone: "ok" },
    ],
    metric: { label: "Auto-resolved", value: "73%", delta: "+9pts" },
  },
  business: {
    layout: "funnel",
    accent: "slate",
    caption: "Request → Approve → Execute → Archive",
    nodes: [
      { id: "r", label: "Request", icon: "FileText", status: "done" },
      { id: "p", label: "Approve", icon: "CheckCircle2", status: "active" },
      { id: "e", label: "Execute", icon: "Settings", status: "idle" },
      { id: "a", label: "Archive", icon: "Archive", status: "idle" },
    ],
    edges: [edge("r", "p"), edge("p", "e"), edge("e", "a")],
    activities: [
      { title: "PO #4821 approved", meta: "Finance", tone: "ok" },
      { title: "Vendor notified", meta: "Email + portal", tone: "info" },
      { title: "Audit log written", meta: "Immutable", tone: "ok" },
    ],
    metric: { label: "Cycle time", value: "2.1d", delta: "-64%" },
  },
  crm: {
    layout: "pipeline",
    accent: "emerald",
    caption: "Lead → Qualify → Pipeline → Won",
    nodes: [
      { id: "l", label: "Lead", icon: "UserPlus", status: "done" },
      { id: "q", label: "Qualify", icon: "Target", status: "active" },
      { id: "p", label: "Pipeline", icon: "Kanban", status: "idle" },
      { id: "w", label: "Won", icon: "Trophy", status: "idle" },
    ],
    edges: [edge("l", "q"), edge("q", "p"), edge("p", "w")],
    activities: [
      { title: "Lead scored 82", meta: "HubSpot", tone: "ok" },
      { title: "Owner assigned", meta: "Jordan · Sales", tone: "info" },
      { title: "Deal created", meta: "$12.4k", tone: "ok" },
    ],
    metric: { label: "Pipeline velocity", value: "4.2×", delta: "+31%" },
  },
  api: {
    layout: "mesh",
    accent: "cyan",
    caption: "Source → Transform → Sync → Monitor",
    nodes: [
      { id: "s", label: "Source", icon: "Server", status: "done" },
      { id: "t", label: "Transform", icon: "RefreshCw", status: "active" },
      { id: "d", label: "Destination", icon: "Database", status: "idle" },
      { id: "m", label: "Monitor", icon: "Activity", status: "idle" },
    ],
    edges: [edge("s", "t"), edge("t", "d"), edge("d", "m"), edge("s", "m")],
    activities: [
      { title: "Webhook received", meta: "200 OK · 42ms", tone: "ok" },
      { title: "Payload mapped", meta: "14 fields", tone: "info" },
      { title: "Retry budget healthy", meta: "0 failures", tone: "ok" },
    ],
    metric: { label: "Sync latency", value: "118ms", delta: "p95" },
  },
  zapier: {
    layout: "flow",
    accent: "amber",
    caption: "Zap trigger → Filter → Paths → Actions",
    nodes: [
      { id: "z", label: "Zap", icon: "Zap", status: "active" },
      { id: "f", label: "Filter", icon: "Filter", status: "idle" },
      { id: "p", label: "Paths", icon: "GitBranch", status: "idle" },
      { id: "a", label: "Actions", icon: "Layers", status: "idle" },
    ],
    edges: [edge("z", "f"), edge("f", "p"), edge("p", "a")],
    activities: [
      { title: "Zap ran", meta: "Gmail → Sheets", tone: "ok" },
      { title: "Filter passed", meta: "Subject match", tone: "info" },
      { title: "3 steps complete", meta: "0.9s", tone: "ok" },
    ],
    metric: { label: "Zaps live", value: "86", delta: "stable" },
  },
  make: {
    layout: "hub",
    accent: "violet",
    caption: "Scenario · Modules · Router · Error handler",
    nodes: [
      { id: "sc", label: "Scenario", icon: "GitBranch", status: "active" },
      { id: "mo", label: "Modules", icon: "Boxes", status: "idle" },
      { id: "ro", label: "Router", icon: "Split", status: "idle" },
      { id: "er", label: "Errors", icon: "ShieldAlert", status: "idle" },
    ],
    edges: [edge("sc", "mo"), edge("mo", "ro"), edge("ro", "er")],
    activities: [
      { title: "Iterator batch", meta: "50 records", tone: "info" },
      { title: "Router → Path B", meta: "Priority", tone: "ok" },
      { title: "Error handler idle", meta: "Clean run", tone: "ok" },
    ],
    metric: { label: "Ops used", value: "12.4k", delta: "month" },
  },
  n8n: {
    layout: "flow",
    accent: "rose",
    caption: "Webhook → Code → AI → Destination",
    nodes: [
      { id: "w", label: "Webhook", icon: "Globe", status: "done" },
      { id: "c", label: "Code", icon: "Code2", status: "active" },
      { id: "ai", label: "AI Node", icon: "Bot", status: "idle" },
      { id: "out", label: "Output", icon: "Send", status: "idle" },
    ],
    edges: [edge("w", "c"), edge("c", "ai"), edge("ai", "out")],
    activities: [
      { title: "Self-hosted run", meta: "Queue worker", tone: "info" },
      { title: "JS transform OK", meta: "42ms", tone: "ok" },
      { title: "Pushed to Postgres", meta: "Insert ×12", tone: "ok" },
    ],
    metric: { label: "Workflows", value: "64", delta: "prod" },
  },
  openai: {
    layout: "hub",
    accent: "emerald",
    caption: "Prompt → GPT → Tools → Response",
    nodes: [
      { id: "p", label: "Prompt", icon: "MessageSquare", status: "done" },
      { id: "g", label: "GPT", icon: "Sparkles", status: "active" },
      { id: "t", label: "Tools", icon: "Wrench", status: "idle" },
      { id: "r", label: "Reply", icon: "Send", status: "idle" },
    ],
    edges: [edge("p", "g"), edge("g", "t"), edge("t", "r"), edge("g", "r")],
    activities: [
      { title: "Tokens: 1,842", meta: "gpt-4.1", tone: "info" },
      { title: "Tool call: search", meta: "KB hit", tone: "ok" },
      { title: "Response streamed", meta: "1.2s TTFB", tone: "ok" },
    ],
    metric: { label: "Avg quality", value: "4.8★", delta: "eval" },
  },
  claude: {
    layout: "funnel",
    accent: "amber",
    caption: "Document → Claude → Extract → Route",
    nodes: [
      { id: "d", label: "Document", icon: "FileText", status: "done" },
      { id: "c", label: "Claude", icon: "Bot", status: "active" },
      { id: "e", label: "Extract", icon: "ScanText", status: "idle" },
      { id: "r", label: "Route", icon: "Share2", status: "idle" },
    ],
    edges: [edge("d", "c"), edge("c", "e"), edge("e", "r")],
    activities: [
      { title: "PDF parsed", meta: "28 pages", tone: "info" },
      { title: "Entities extracted", meta: "14 fields", tone: "ok" },
      { title: "Sent to legal queue", meta: "Priority", tone: "ok" },
    ],
    metric: { label: "Accuracy", value: "96%", delta: "spot check" },
  },
  gemini: {
    layout: "mesh",
    accent: "blue",
    caption: "Image + Text → Gemini → Insight → Action",
    nodes: [
      { id: "i", label: "Vision", icon: "Image", status: "done" },
      { id: "g", label: "Gemini", icon: "Gem", status: "active" },
      { id: "k", label: "Insight", icon: "Lightbulb", status: "idle" },
      { id: "a", label: "Action", icon: "Rocket", status: "idle" },
    ],
    edges: [edge("i", "g"), edge("g", "k"), edge("k", "a")],
    activities: [
      { title: "Multimodal input", meta: "Photo + note", tone: "info" },
      { title: "Defect flagged", meta: "High severity", tone: "warn" },
      { title: "Ticket opened", meta: "QA board", tone: "ok" },
    ],
    metric: { label: "Latency", value: "840ms", delta: "median" },
  },
  whatsapp: {
    layout: "flow",
    accent: "emerald",
    caption: "Message → Bot → CRM → Agent handoff",
    nodes: [
      { id: "m", label: "WhatsApp", icon: "MessageCircle", status: "done" },
      { id: "b", label: "Bot", icon: "Bot", status: "active" },
      { id: "c", label: "CRM", icon: "Users", status: "idle" },
      { id: "h", label: "Human", icon: "Headphones", status: "idle" },
    ],
    edges: [edge("m", "b"), edge("b", "c"), edge("b", "h")],
    activities: [
      { title: "Order status asked", meta: "+1 · template", tone: "info" },
      { title: "Auto-reply sent", meta: "ETA 2 days", tone: "ok" },
      { title: "Logged to HubSpot", meta: "Contact timeline", tone: "ok" },
    ],
    metric: { label: "Auto-handled", value: "85%", delta: "chats" },
  },
  email: {
    layout: "flow",
    accent: "blue",
    caption: "Inbox → Classify → Sequence → CRM",
    nodes: [
      { id: "i", label: "Inbox", icon: "Mail", status: "done" },
      { id: "c", label: "Classify", icon: "Sparkles", status: "active" },
      { id: "s", label: "Sequence", icon: "ListOrdered", status: "idle" },
      { id: "r", label: "CRM", icon: "Users", status: "idle" },
    ],
    edges: [edge("i", "c"), edge("c", "s"), edge("s", "r")],
    activities: [
      { title: "Intent: billing", meta: "AI tag", tone: "info" },
      { title: "Sequence started", meta: "3 touches", tone: "ok" },
      { title: "Deal stage updated", meta: "Negotiation", tone: "ok" },
    ],
    metric: { label: "Open rate", value: "48%", delta: "+6pts" },
  },
  leads: {
    layout: "pipeline",
    accent: "cyan",
    caption: "Capture → Enrich → Score → Route",
    nodes: [
      { id: "c", label: "Capture", icon: "Radar", status: "done" },
      { id: "e", label: "Enrich", icon: "Database", status: "active" },
      { id: "s", label: "Score", icon: "Gauge", status: "idle" },
      { id: "r", label: "Route", icon: "Share2", status: "idle" },
    ],
    edges: [edge("c", "e"), edge("e", "s"), edge("s", "r")],
    activities: [
      { title: "New lead ingested", meta: "LinkedIn form", tone: "info" },
      { title: "Firmographics filled", meta: "Clearbit", tone: "ok" },
      { title: "Routed to AE", meta: "West region", tone: "ok" },
    ],
    metric: { label: "Qualified / day", value: "142", delta: "+3×" },
  },
  appointments: {
    layout: "flow",
    accent: "violet",
    caption: "Request → Availability → Book → Remind",
    nodes: [
      { id: "r", label: "Request", icon: "Calendar", status: "done" },
      { id: "a", label: "Slots", icon: "Clock", status: "active" },
      { id: "b", label: "Book", icon: "CalendarCheck", status: "idle" },
      { id: "m", label: "Remind", icon: "Bell", status: "idle" },
    ],
    edges: [edge("r", "a"), edge("a", "b"), edge("b", "m")],
    activities: [
      { title: "Slot held", meta: "Thu 2:30 PM", tone: "info" },
      { title: "Meet link created", meta: "Google Meet", tone: "ok" },
      { title: "SMS reminder queued", meta: "T-24h", tone: "ok" },
    ],
    metric: { label: "No-show rate", value: "8%", delta: "-22pts" },
  },
  chatbots: {
    layout: "hub",
    accent: "blue",
    caption: "Visitor → Bot → Knowledge → Escalate",
    nodes: [
      { id: "v", label: "Visitor", icon: "User", status: "done" },
      { id: "b", label: "Chatbot", icon: "MessagesSquare", status: "active" },
      { id: "k", label: "Knowledge", icon: "BookOpen", status: "idle" },
      { id: "e", label: "Escalate", icon: "Headphones", status: "idle" },
    ],
    edges: [edge("v", "b"), edge("b", "k"), edge("b", "e")],
    activities: [
      { title: "FAQ matched", meta: "Shipping policy", tone: "ok" },
      { title: "KB article cited", meta: "Doc #204", tone: "info" },
      { title: "Handoff ready", meta: "CS queue", tone: "warn" },
    ],
    metric: { label: "Containment", value: "71%", delta: "+12pts" },
  },
  voice: {
    layout: "dial",
    accent: "rose",
    caption: "Call → Voice AI → Intent → Transfer",
    nodes: [
      { id: "c", label: "Call", icon: "Phone", status: "done" },
      { id: "v", label: "Voice AI", icon: "Mic", status: "active" },
      { id: "i", label: "Intent", icon: "Brain", status: "idle" },
      { id: "t", label: "Transfer", icon: "PhoneForwarded", status: "idle" },
    ],
    edges: [edge("c", "v"), edge("v", "i"), edge("i", "t")],
    activities: [
      { title: "Greeting played", meta: "Natural TTS", tone: "info" },
      { title: "Intent: booking", meta: "0.91 score", tone: "ok" },
      { title: "Warm transfer", meta: "Ext 204", tone: "ok" },
    ],
    metric: { label: "Tier-1 automated", value: "68%", delta: "calls" },
  },
  support: {
    layout: "funnel",
    accent: "cyan",
    caption: "Customer → AI → Knowledge → Human",
    nodes: [
      { id: "c", label: "Customer", icon: "User", status: "done" },
      { id: "a", label: "AI Assist", icon: "Bot", status: "active" },
      { id: "k", label: "Knowledge", icon: "BookOpen", status: "idle" },
      { id: "h", label: "Human", icon: "Headphones", status: "idle" },
    ],
    edges: [edge("c", "a"), edge("a", "k"), edge("a", "h")],
    activities: [
      { title: "Ticket triaged", meta: "Priority: med", tone: "info" },
      { title: "Draft reply ready", meta: "Review queue", tone: "ok" },
      { title: "Escalated L2", meta: "Billing dispute", tone: "warn" },
    ],
    metric: { label: "First response", value: "<2m", delta: "median" },
  },
  internal: {
    layout: "mesh",
    accent: "slate",
    caption: "HR · Finance · Ops · Alerts",
    nodes: [
      { id: "hr", label: "HR", icon: "Users", status: "done" },
      { id: "fi", label: "Finance", icon: "Landmark", status: "active" },
      { id: "op", label: "Ops", icon: "Settings", status: "idle" },
      { id: "al", label: "Alerts", icon: "Bell", status: "idle" },
    ],
    edges: [edge("hr", "fi"), edge("fi", "op"), edge("op", "al"), edge("hr", "al")],
    activities: [
      { title: "Onboarding checklist", meta: "Day 1 complete", tone: "ok" },
      { title: "Expense approved", meta: "$340", tone: "info" },
      { title: "SLA ping sent", meta: "Ops channel", tone: "ok" },
    ],
    metric: { label: "Hours saved / wk", value: "38", delta: "team" },
  },
  data: {
    layout: "flow",
    accent: "violet",
    caption: "Extract → Clean → Load → Warehouse",
    nodes: [
      { id: "e", label: "Extract", icon: "Download", status: "done" },
      { id: "c", label: "Clean", icon: "Sparkles", status: "active" },
      { id: "l", label: "Load", icon: "Upload", status: "idle" },
      { id: "w", label: "Warehouse", icon: "Database", status: "idle" },
    ],
    edges: [edge("e", "c"), edge("c", "l"), edge("l", "w")],
    activities: [
      { title: "ETL job #291", meta: "Running", tone: "info" },
      { title: "Duplicates removed", meta: "1,204 rows", tone: "ok" },
      { title: "Warehouse synced", meta: "Snowflake", tone: "ok" },
    ],
    metric: { label: "Freshness", value: "4m", delta: "lag" },
  },
  dashboards: {
    layout: "radar",
    accent: "blue",
    caption: "Sources → Metrics → Charts → Alerts",
    nodes: [
      { id: "s", label: "Sources", icon: "Database", status: "done" },
      { id: "m", label: "Metrics", icon: "Gauge", status: "active" },
      { id: "c", label: "Charts", icon: "BarChart3", status: "idle" },
      { id: "a", label: "Alerts", icon: "Bell", status: "idle" },
    ],
    edges: [edge("s", "m"), edge("m", "c"), edge("c", "a")],
    activities: [
      { title: "KPI board refreshed", meta: "Every 5m", tone: "info" },
      { title: "Revenue spike", meta: "+12% WoW", tone: "ok" },
      { title: "Alert: ASA > 45s", meta: "Queue B", tone: "warn" },
    ],
    metric: { label: "Live widgets", value: "24", delta: "board" },
  },
  web: {
    layout: "flow",
    accent: "cyan",
    caption: "Browse → Extract → Validate → Write",
    nodes: [
      { id: "b", label: "Browser", icon: "Globe", status: "done" },
      { id: "e", label: "Extract", icon: "ScanSearch", status: "active" },
      { id: "v", label: "Validate", icon: "ShieldCheck", status: "idle" },
      { id: "w", label: "Write", icon: "FileOutput", status: "idle" },
    ],
    edges: [edge("b", "e"), edge("e", "v"), edge("v", "w")],
    activities: [
      { title: "Session started", meta: "Headless Chrome", tone: "info" },
      { title: "48 rows scraped", meta: "Schema OK", tone: "ok" },
      { title: "Sheet updated", meta: "Append", tone: "ok" },
    ],
    metric: { label: "Success rate", value: "99.1%", delta: "jobs" },
  },
  consulting: {
    layout: "funnel",
    accent: "amber",
    caption: "Audit → Roadmap → Pilot → Scale",
    nodes: [
      { id: "a", label: "Audit", icon: "Search", status: "done" },
      { id: "r", label: "Roadmap", icon: "Map", status: "active" },
      { id: "p", label: "Pilot", icon: "Rocket", status: "idle" },
      { id: "s", label: "Scale", icon: "TrendingUp", status: "idle" },
    ],
    edges: [edge("a", "r"), edge("r", "p"), edge("p", "s")],
    activities: [
      { title: "12 processes mapped", meta: "Workshop", tone: "info" },
      { title: "ROI model ready", meta: "3 scenarios", tone: "ok" },
      { title: "Pilot #1 scoped", meta: "2 weeks", tone: "ok" },
    ],
    metric: { label: "Projected ROI", value: "340%", delta: "Yr1" },
  },

  // Call center
  "3cx": {
    layout: "dial",
    accent: "blue",
    caption: "Call → IVR → Queue → Agent → Recording → Analytics",
    nodes: [
      { id: "in", label: "Incoming", icon: "PhoneIncoming", status: "done" },
      { id: "ivr", label: "IVR", icon: "ListTree", status: "active" },
      { id: "q", label: "Queue", icon: "Layers", status: "idle" },
      { id: "ag", label: "Agent", icon: "Headphones", status: "idle" },
      { id: "rec", label: "Record", icon: "Disc", status: "idle" },
      { id: "an", label: "Analytics", icon: "LineChart", status: "idle" },
    ],
    edges: [
      edge("in", "ivr"),
      edge("ivr", "q"),
      edge("q", "ag"),
      edge("ag", "rec"),
      edge("rec", "an"),
    ],
    activities: [
      { title: "IVR option 2", meta: "Support", tone: "info" },
      { title: "Queue wait 12s", meta: "Skills match", tone: "ok" },
      { title: "Call recorded", meta: "Linked to CRM", tone: "ok" },
    ],
    metric: { label: "Active calls", value: "24", delta: "live" },
  },
  vicidial: {
    layout: "dial",
    accent: "rose",
    caption: "Lead → Predictive → Agent → CRM → Report",
    nodes: [
      { id: "l", label: "Lead", icon: "UserPlus", status: "done" },
      { id: "d", label: "Dialer", icon: "FastForward", status: "active" },
      { id: "a", label: "Agent", icon: "Headphones", status: "idle" },
      { id: "c", label: "CRM", icon: "Users", status: "idle" },
      { id: "r", label: "Report", icon: "BarChart3", status: "idle" },
    ],
    edges: [edge("l", "d"), edge("d", "a"), edge("a", "c"), edge("c", "r")],
    activities: [
      { title: "Hopper loaded", meta: "2,400 leads", tone: "info" },
      { title: "Connect ratio 31%", meta: "Predictive", tone: "ok" },
      { title: "Disposition: SALE", meta: "Agent 6666", tone: "ok" },
    ],
    metric: { label: "Talk time", value: "48m", delta: "/agent" },
  },
  freepbx: {
    layout: "hub",
    accent: "emerald",
    caption: "Trunk → Extensions → Routes → Apps",
    nodes: [
      { id: "t", label: "Trunks", icon: "Cable", status: "done" },
      { id: "e", label: "Extensions", icon: "Phone", status: "active" },
      { id: "r", label: "Routes", icon: "Route", status: "idle" },
      { id: "a", label: "Apps", icon: "Blocks", status: "idle" },
    ],
    edges: [edge("t", "e"), edge("e", "r"), edge("r", "a")],
    activities: [
      { title: "SIP trunk up", meta: "Primary carrier", tone: "ok" },
      { title: "40 extensions", meta: "Provisioned", tone: "info" },
      { title: "Failover tested", meta: "Secondary OK", tone: "ok" },
    ],
    metric: { label: "Uptime", value: "99.98%", delta: "30d" },
  },
  asterisk: {
    layout: "mesh",
    accent: "slate",
    caption: "Dialplan → Channels → Apps → CDR",
    nodes: [
      { id: "d", label: "Dialplan", icon: "Code2", status: "active" },
      { id: "c", label: "Channels", icon: "Radio", status: "idle" },
      { id: "a", label: "Apps", icon: "Puzzle", status: "idle" },
      { id: "cdr", label: "CDR", icon: "FileText", status: "idle" },
    ],
    edges: [edge("d", "c"), edge("c", "a"), edge("a", "cdr")],
    activities: [
      { title: "Context matched", meta: "from-internal", tone: "info" },
      { title: "Channel up", meta: "PJSIP/204", tone: "ok" },
      { title: "CDR written", meta: "MySQL", tone: "ok" },
    ],
    metric: { label: "Channels", value: "86", delta: "peak" },
  },
  pbx: {
    layout: "hub",
    accent: "blue",
    caption: "Design → Deploy → Provision → Monitor",
    nodes: [
      { id: "d", label: "Design", icon: "Compass", status: "done" },
      { id: "p", label: "Deploy", icon: "Server", status: "active" },
      { id: "v", label: "Provision", icon: "HardDrive", status: "idle" },
      { id: "m", label: "Monitor", icon: "Activity", status: "idle" },
    ],
    edges: [edge("d", "p"), edge("p", "v"), edge("v", "m")],
    activities: [
      { title: "Architecture signed", meta: "HA pair", tone: "ok" },
      { title: "VM cluster live", meta: "Cloud", tone: "info" },
      { title: "Health checks green", meta: "All nodes", tone: "ok" },
    ],
    metric: { label: "Sites", value: "6", delta: "unified" },
  },
  voip: {
    layout: "flow",
    accent: "cyan",
    caption: "SIP → QoS → Softphone → Failover",
    nodes: [
      { id: "s", label: "SIP", icon: "Cable", status: "done" },
      { id: "q", label: "QoS", icon: "Wifi", status: "active" },
      { id: "p", label: "Softphone", icon: "Smartphone", status: "idle" },
      { id: "f", label: "Failover", icon: "Shield", status: "idle" },
    ],
    edges: [edge("s", "q"), edge("q", "p"), edge("p", "f")],
    activities: [
      { title: "MOS 4.3", meta: "Excellent", tone: "ok" },
      { title: "Jitter buffered", meta: "18ms", tone: "info" },
      { title: "Secondary trunk idle", meta: "Standby", tone: "ok" },
    ],
    metric: { label: "Call completion", value: "99.99%", delta: "SLA" },
  },
  recording: {
    layout: "funnel",
    accent: "violet",
    caption: "Call → Capture → Encrypt → Search",
    nodes: [
      { id: "c", label: "Call", icon: "Phone", status: "done" },
      { id: "r", label: "Capture", icon: "Disc", status: "active" },
      { id: "e", label: "Encrypt", icon: "Lock", status: "idle" },
      { id: "s", label: "Search", icon: "Search", status: "idle" },
    ],
    edges: [edge("c", "r"), edge("r", "e"), edge("e", "s")],
    activities: [
      { title: "Recording started", meta: "Stereo", tone: "info" },
      { title: "AES stored", meta: "S3 vault", tone: "ok" },
      { title: "Indexed for CRM", meta: "Call ID linked", tone: "ok" },
    ],
    metric: { label: "Retention", value: "7 yrs", delta: "policy" },
  },
  routing: {
    layout: "mesh",
    accent: "amber",
    caption: "DID → Rules → Skills → Agent",
    nodes: [
      { id: "d", label: "DID", icon: "PhoneIncoming", status: "done" },
      { id: "r", label: "Rules", icon: "Route", status: "active" },
      { id: "s", label: "Skills", icon: "Award", status: "idle" },
      { id: "a", label: "Agent", icon: "Headphones", status: "idle" },
    ],
    edges: [edge("d", "r"), edge("r", "s"), edge("s", "a")],
    activities: [
      { title: "Time-of-day match", meta: "Business hours", tone: "info" },
      { title: "Skill: billing", meta: "Priority 1", tone: "ok" },
      { title: "Ringing agent 118", meta: "Available", tone: "ok" },
    ],
    metric: { label: "Wrong dept", value: "-30%", delta: "transfers" },
  },
  ivr: {
    layout: "funnel",
    accent: "blue",
    caption: "Welcome → Menu → DTMF/NLU → Route",
    nodes: [
      { id: "w", label: "Welcome", icon: "Volume2", status: "done" },
      { id: "m", label: "Menu", icon: "ListTree", status: "active" },
      { id: "i", label: "Input", icon: "Keyboard", status: "idle" },
      { id: "r", label: "Route", icon: "Share2", status: "idle" },
    ],
    edges: [edge("w", "m"), edge("m", "i"), edge("i", "r")],
    activities: [
      { title: "Language: EN", meta: "Selected", tone: "info" },
      { title: "Option 3 pressed", meta: "Scheduling", tone: "ok" },
      { title: "Forwarded to queue", meta: "Clinic desk", tone: "ok" },
    ],
    metric: { label: "Self-serve", value: "54%", delta: "IVR exits" },
  },
  sip: {
    layout: "flow",
    accent: "cyan",
    caption: "Carrier → Trunk → PBX → Endpoints",
    nodes: [
      { id: "c", label: "Carrier", icon: "Radio", status: "done" },
      { id: "t", label: "Trunk", icon: "Cable", status: "active" },
      { id: "p", label: "PBX", icon: "Server", status: "idle" },
      { id: "e", label: "Phones", icon: "Phone", status: "idle" },
    ],
    edges: [edge("c", "t"), edge("t", "p"), edge("p", "e")],
    activities: [
      { title: "Registration OK", meta: "Primary SIP", tone: "ok" },
      { title: "Codec: G.722", meta: "Negotiated", tone: "info" },
      { title: "Endpoints online", meta: "118 / 120", tone: "ok" },
    ],
    metric: { label: "Concurrent", value: "64", delta: "channels" },
  },
  queue: {
    layout: "radar",
    accent: "rose",
    caption: "Caller → Strategy → Wait → Agent",
    nodes: [
      { id: "c", label: "Caller", icon: "PhoneIncoming", status: "done" },
      { id: "s", label: "Strategy", icon: "Layers", status: "active" },
      { id: "w", label: "Wait", icon: "Clock", status: "idle" },
      { id: "a", label: "Agent", icon: "Headphones", status: "idle" },
    ],
    edges: [edge("c", "s"), edge("s", "w"), edge("w", "a")],
    activities: [
      { title: "Priority bump", meta: "VIP tag", tone: "info" },
      { title: "Callback offered", meta: "Position 4", tone: "warn" },
      { title: "Connected", meta: "ASA 18s", tone: "ok" },
    ],
    metric: { label: "Abandon rate", value: "4.2%", delta: "-40%" },
  },
  predictive: {
    layout: "dial",
    accent: "amber",
    caption: "List → Pace → Connect → Disposition",
    nodes: [
      { id: "l", label: "List", icon: "List", status: "done" },
      { id: "p", label: "Pace", icon: "Gauge", status: "active" },
      { id: "c", label: "Connect", icon: "PhoneCall", status: "idle" },
      { id: "d", label: "Dispo", icon: "ClipboardCheck", status: "idle" },
    ],
    edges: [edge("l", "p"), edge("p", "c"), edge("c", "d")],
    activities: [
      { title: "Dial level 2.6", meta: "Adaptive", tone: "info" },
      { title: "Drop % 0.1", meta: "Compliant", tone: "ok" },
      { title: "Talking agents 96", meta: "Live", tone: "ok" },
    ],
    metric: { label: "Connects / hr", value: "38", delta: "/agent" },
  },
  progressive: {
    layout: "flow",
    accent: "emerald",
    caption: "Preview → Dial → Talk → Log",
    nodes: [
      { id: "p", label: "Preview", icon: "Eye", status: "done" },
      { id: "d", label: "Dial", icon: "StepForward", status: "active" },
      { id: "t", label: "Talk", icon: "Headphones", status: "idle" },
      { id: "l", label: "Log", icon: "ClipboardList", status: "idle" },
    ],
    edges: [edge("p", "d"), edge("d", "t"), edge("t", "l")],
    activities: [
      { title: "Lead previewed", meta: "8s window", tone: "info" },
      { title: "Agent accepted", meta: "Dial out", tone: "ok" },
      { title: "Notes synced", meta: "CRM", tone: "ok" },
    ],
    metric: { label: "Compliance", value: "100%", delta: "DNC" },
  },
  inbound: {
    layout: "dial",
    accent: "blue",
    caption: "DID → Screen-pop → Agent → Wrap",
    nodes: [
      { id: "d", label: "Inbound", icon: "PhoneIncoming", status: "done" },
      { id: "s", label: "Screen-pop", icon: "Monitor", status: "active" },
      { id: "a", label: "Agent", icon: "Headphones", status: "idle" },
      { id: "w", label: "Wrap-up", icon: "CheckCircle2", status: "idle" },
    ],
    edges: [edge("d", "s"), edge("s", "a"), edge("a", "w")],
    activities: [
      { title: "Caller ID matched", meta: "CRM contact", tone: "ok" },
      { title: "History loaded", meta: "Last 5 tickets", tone: "info" },
      { title: "Disposition saved", meta: "Resolved", tone: "ok" },
    ],
    metric: { label: "ASA", value: "22s", delta: "today" },
  },
  outbound: {
    layout: "pipeline",
    accent: "rose",
    caption: "Campaign → Dial → Pitch → Close",
    nodes: [
      { id: "c", label: "Campaign", icon: "Megaphone", status: "done" },
      { id: "d", label: "Dial", icon: "PhoneOutgoing", status: "active" },
      { id: "p", label: "Pitch", icon: "MessageSquare", status: "idle" },
      { id: "x", label: "Close", icon: "Trophy", status: "idle" },
    ],
    edges: [edge("c", "d"), edge("d", "p"), edge("p", "x")],
    activities: [
      { title: "Script v3 loaded", meta: "Compliance OK", tone: "info" },
      { title: "Interest detected", meta: "AI assist", tone: "ok" },
      { title: "Deal created", meta: "$890", tone: "ok" },
    ],
    metric: { label: "Conversion", value: "2.8×", delta: "vs manual" },
  },
  "cloud-pbx": {
    layout: "hub",
    accent: "cyan",
    caption: "Sites → Cloud PBX → Users → Reporting",
    nodes: [
      { id: "s", label: "Sites", icon: "Building2", status: "done" },
      { id: "c", label: "Cloud PBX", icon: "Cloud", status: "active" },
      { id: "u", label: "Users", icon: "Users", status: "idle" },
      { id: "r", label: "Reports", icon: "BarChart3", status: "idle" },
    ],
    edges: [edge("s", "c"), edge("c", "u"), edge("c", "r")],
    activities: [
      { title: "12 sites linked", meta: "VPN + SBC", tone: "ok" },
      { title: "Shared queues", meta: "Central", tone: "info" },
      { title: "Executive dashboard", meta: "Live", tone: "ok" },
    ],
    metric: { label: "Cost save", value: "35%", delta: "YoY" },
  },
  analytics: {
    layout: "radar",
    accent: "violet",
    caption: "CDR → Metrics → Wallboard → Insights",
    nodes: [
      { id: "c", label: "CDR", icon: "Database", status: "done" },
      { id: "m", label: "Metrics", icon: "LineChart", status: "active" },
      { id: "w", label: "Wallboard", icon: "Monitor", status: "idle" },
      { id: "i", label: "Insights", icon: "Lightbulb", status: "idle" },
    ],
    edges: [edge("c", "m"), edge("m", "w"), edge("w", "i")],
    activities: [
      { title: "AHT trending down", meta: "-14s", tone: "ok" },
      { title: "SLA 98% met", meta: "Queue A", tone: "ok" },
      { title: "Coach alert", meta: "Agent 204", tone: "warn" },
    ],
    metric: { label: "Abandon", value: "3.1%", delta: "-1.4pts" },
  },
  "crm-int": {
    layout: "flow",
    accent: "emerald",
    caption: "Call → Screen-pop → Log → Disposition",
    nodes: [
      { id: "c", label: "Call", icon: "Phone", status: "done" },
      { id: "s", label: "Screen-pop", icon: "MonitorSmartphone", status: "active" },
      { id: "l", label: "Auto-log", icon: "FilePlus", status: "idle" },
      { id: "d", label: "Dispo", icon: "ClipboardCheck", status: "idle" },
    ],
    edges: [edge("c", "s"), edge("s", "l"), edge("l", "d")],
    activities: [
      { title: "Contact matched", meta: "HubSpot", tone: "ok" },
      { title: "Activity logged", meta: "0 clicks", tone: "info" },
      { title: "Stage advanced", meta: "Qualified", tone: "ok" },
    ],
    metric: { label: "Calls logged", value: "100%", delta: "auto" },
  },
  autodialer: {
    layout: "dial",
    accent: "amber",
    caption: "List → Auto-dial → Detect → Agent",
    nodes: [
      { id: "l", label: "List", icon: "List", status: "done" },
      { id: "a", label: "Auto-dial", icon: "Repeat", status: "active" },
      { id: "d", label: "AMD", icon: "AudioLines", status: "idle" },
      { id: "ag", label: "Agent", icon: "Headphones", status: "idle" },
    ],
    edges: [edge("l", "a"), edge("a", "d"), edge("d", "ag")],
    activities: [
      { title: "Retry schedule", meta: "Max 3", tone: "info" },
      { title: "Human detected", meta: "AMD pass", tone: "ok" },
      { title: "Agent bridged", meta: "0.8s", tone: "ok" },
    ],
    metric: { label: "DNC filtered", value: "100%", delta: "safe" },
  },
  "agent-dash": {
    layout: "radar",
    accent: "blue",
    caption: "Presence → Stats → Scripts → Actions",
    nodes: [
      { id: "p", label: "Presence", icon: "CircleDot", status: "done" },
      { id: "s", label: "Stats", icon: "BarChart3", status: "active" },
      { id: "sc", label: "Scripts", icon: "ScrollText", status: "idle" },
      { id: "a", label: "Actions", icon: "MousePointerClick", status: "idle" },
    ],
    edges: [edge("p", "s"), edge("s", "sc"), edge("sc", "a")],
    activities: [
      { title: "Status: Available", meta: "Agent 118", tone: "ok" },
      { title: "Calls today: 47", meta: "AHT 3:12", tone: "info" },
      { title: "Next best action", meta: "Upsell hint", tone: "ok" },
    ],
    metric: { label: "Occupancy", value: "81%", delta: "target 85" },
  },
  remote: {
    layout: "mesh",
    accent: "slate",
    caption: "Home → VPN → Softphone → QA",
    nodes: [
      { id: "h", label: "Remote", icon: "Home", status: "done" },
      { id: "v", label: "VPN", icon: "Shield", status: "active" },
      { id: "s", label: "Softphone", icon: "Laptop", status: "idle" },
      { id: "q", label: "QA", icon: "Headphones", status: "idle" },
    ],
    edges: [edge("h", "v"), edge("v", "s"), edge("s", "q")],
    activities: [
      { title: "Tunnel connected", meta: "WireGuard", tone: "ok" },
      { title: "Softphone registered", meta: "WebRTC", tone: "info" },
      { title: "Whisper coaching", meta: "Supervisor", tone: "ok" },
    ],
    metric: { label: "Remote agents", value: "92", delta: "online" },
  },
};

export function getServiceWorkflow(serviceId: string): ServiceWorkflowDef {
  return (
    SERVICE_WORKFLOWS[serviceId] ?? {
      layout: "flow",
      accent: "blue",
      caption: "Input → Process → Output",
      nodes: [
        { id: "a", label: "Input", icon: "Inbox", status: "done" },
        { id: "b", label: "Process", icon: "Cog", status: "active" },
        { id: "c", label: "Output", icon: "Send", status: "idle" },
      ],
      edges: [edge("a", "b"), edge("b", "c")],
      activities: [
        { title: "Workflow running", meta: "Live", tone: "info" },
        { title: "Step complete", meta: "OK", tone: "ok" },
      ],
      metric: { label: "Status", value: "Live", delta: "demo" },
    }
  );
}
